version: 2

builds:
  - binary: tugu
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
